"""
Project Atlas
Phase 3 — Business Data Validation

Validates the nine clean business-process datasets generated by
generate_business_data.py.

Default mode validates the clean baseline.

Final mode validates the intentionally imperfect source data after
quality issues have been injected.
"""

from pathlib import Path
import sys

import numpy as np
import pandas as pd


# ============================================================
# Paths
# ============================================================

PROJECT_ROOT = Path(__file__).resolve().parents[2]
RAW_DATA_DIR = PROJECT_ROOT / "data" / "raw"


# ============================================================
# Expected Counts
# ============================================================

EXPECTED_COUNTS = {
    "sales.csv": 500_000,
    "production.csv": 200_000,
    "maintenance.csv": 50_000,
    "financial_transactions.csv": 300_000,
    "budget.csv": 20_000,
    "energy.csv": 100_000,
    "emissions.csv": 100_000,
    "waste.csv": 100_000,
    "inventory.csv": 500_000,
}


# ============================================================
# Required Columns
# ============================================================

REQUIRED_COLUMNS = {
    "sales.csv": [
        "transaction_id",
        "transaction_date",
        "account_id",
        "customer_id",
        "product_id",
        "location_id",
        "quantity",
        "unit_price",
        "discount_amount",
        "revenue",
    ],
    "production.csv": [
        "production_id",
        "production_date",
        "product_id",
        "location_id",
        "machine_id",
        "employee_id",
        "planned_quantity",
        "produced_quantity",
        "defect_quantity",
        "production_hours",
    ],
    "maintenance.csv": [
        "maintenance_id",
        "maintenance_date",
        "location_id",
        "machine_id",
        "employee_id",
        "maintenance_type",
        "maintenance_hours",
        "downtime_hours",
        "maintenance_cost",
    ],
    "financial_transactions.csv": [
        "financial_transaction_id",
        "transaction_date",
        "location_id",
        "transaction_type",
        "category",
        "amount",
    ],
    "budget.csv": [
        "budget_id",
        "budget_date",
        "location_id",
        "budget_category",
        "budget_amount",
    ],
    "energy.csv": [
        "energy_id",
        "measurement_date",
        "location_id",
        "energy_type",
        "consumption",
        "unit",
    ],
    "emissions.csv": [
        "emissions_id",
        "emissions_date",
        "location_id",
        "emission_source",
        "co2e_amount",
        "unit",
    ],
    "waste.csv": [
        "waste_id",
        "waste_date",
        "location_id",
        "waste_type",
        "disposal_method",
        "waste_quantity",
        "unit",
    ],
    "inventory.csv": [
        "inventory_id",
        "inventory_date",
        "product_id",
        "location_id",
        "opening_quantity",
        "received_quantity",
        "issued_quantity",
        "closing_quantity",
        "reorder_point",
    ],
}


# ============================================================
# Helpers
# ============================================================

def load_dataset(filename):
    path = RAW_DATA_DIR / filename

    if not path.exists():
        raise FileNotFoundError(
            f"Required file not found: {path}"
        )

    return pd.read_csv(path)


def load_reference_data():
    files = [
        "accounts.csv",
        "customers.csv",
        "products.csv",
        "locations.csv",
        "employees.csv",
        "machines.csv",
    ]

    return {
        filename: load_dataset(filename)
        for filename in files
    }


def check(condition, passed_message, failed_message):
    if condition:
        print(f"PASS  {passed_message}")
        return True

    print(f"FAIL  {failed_message}")
    return False


def validate_id_relationship(
    child_df,
    child_column,
    parent_df,
    parent_column,
    relationship_name,
):
    child_values = set(
        child_df[child_column]
        .dropna()
        .astype(str)
    )

    parent_values = set(
        parent_df[parent_column]
        .dropna()
        .astype(str)
    )

    invalid = child_values - parent_values

    if not invalid:
        print(
            f"PASS  {relationship_name}"
        )
        return True

    print(
        f"FAIL  {relationship_name}: "
        f"{len(invalid):,} invalid references"
    )

    return False


# ============================================================
# Clean Validation
# ============================================================

def validate_clean_data():

    failures = 0

    print("=" * 60)
    print("Project Atlas — Business Data Validation")
    print("Mode: CLEAN BASELINE")
    print("=" * 60)

    print("\n1. Loading datasets")

    datasets = {}

    for filename in EXPECTED_COUNTS:

        try:
            datasets[filename] = load_dataset(filename)

            print(
                f"Loaded {filename}: "
                f"{len(datasets[filename]):,} records"
            )

        except FileNotFoundError as error:
            print(f"FAIL  {error}")
            failures += 1

    if failures:
        return False

    reference = load_reference_data()

    # --------------------------------------------------------
    # Record counts
    # --------------------------------------------------------

    print("\n2. Record count validation")

    for filename, expected in EXPECTED_COUNTS.items():

        actual = len(datasets[filename])

        if not check(
            actual == expected,
            f"{filename}: expected {expected:,}, found {actual:,}",
            f"{filename}: expected {expected:,}, found {actual:,}",
        ):
            failures += 1

    # --------------------------------------------------------
    # Required columns
    # --------------------------------------------------------

    print("\n3. Required column validation")

    for filename, required in REQUIRED_COLUMNS.items():

        actual_columns = set(
            datasets[filename].columns
        )

        missing = set(required) - actual_columns

        if not check(
            not missing,
            f"{filename}: all required columns present",
            f"{filename}: missing columns {sorted(missing)}",
        ):
            failures += 1

    # --------------------------------------------------------
    # Business-key uniqueness
    # --------------------------------------------------------

    print("\n4. Business-key uniqueness")

    id_columns = {
        "sales.csv": "transaction_id",
        "production.csv": "production_id",
        "maintenance.csv": "maintenance_id",
        "financial_transactions.csv":
            "financial_transaction_id",
        "budget.csv": "budget_id",
        "energy.csv": "energy_id",
        "emissions.csv": "emissions_id",
        "waste.csv": "waste_id",
        "inventory.csv": "inventory_id",
    }

    for filename, column in id_columns.items():

        df = datasets[filename]

        null_count = df[column].isna().sum()
        duplicate_count = df[column].duplicated().sum()

        if not check(
            null_count == 0,
            f"{filename}: {column} contains no nulls",
            f"{filename}: {column} contains {null_count:,} nulls",
        ):
            failures += 1

        if not check(
            duplicate_count == 0,
            f"{filename}: {column} contains no duplicates",
            f"{filename}: {column} contains {duplicate_count:,} duplicates",
        ):
            failures += 1

    # --------------------------------------------------------
    # Required fields
    # --------------------------------------------------------

    print("\n5. Required-field null validation")

    required_non_null = {
        "sales.csv": [
            "transaction_id",
            "transaction_date",
            "account_id",
            "customer_id",
            "product_id",
            "location_id",
        ],
        "production.csv": [
            "production_id",
            "production_date",
            "product_id",
            "location_id",
            "machine_id",
            "employee_id",
        ],
        "maintenance.csv": [
            "maintenance_id",
            "maintenance_date",
            "location_id",
            "machine_id",
            "employee_id",
        ],
        "financial_transactions.csv": [
            "financial_transaction_id",
            "transaction_date",
            "location_id",
            "category",
        ],
        "budget.csv": [
            "budget_id",
            "budget_date",
            "location_id",
            "budget_category",
        ],
        "energy.csv": [
            "energy_id",
            "measurement_date",
            "location_id",
            "energy_type",
        ],
        "emissions.csv": [
            "emissions_id",
            "emissions_date",
            "location_id",
            "emission_source",
        ],
        "waste.csv": [
            "waste_id",
            "waste_date",
            "location_id",
            "waste_type",
        ],
        "inventory.csv": [
            "inventory_id",
            "inventory_date",
            "product_id",
            "location_id",
        ],
    }

    for filename, columns in required_non_null.items():

        df = datasets[filename]

        for column in columns:

            null_count = df[column].isna().sum()

            if not check(
                null_count == 0,
                f"{filename}: {column} contains no nulls",
                f"{filename}: {column} contains {null_count:,} nulls",
            ):
                failures += 1

    # --------------------------------------------------------
    # Foreign-key validation
    # --------------------------------------------------------

    print("\n6. Foreign-key validation")

    accounts = reference["accounts.csv"]
    customers = reference["customers.csv"]
    products = reference["products.csv"]
    locations = reference["locations.csv"]
    employees = reference["employees.csv"]
    machines = reference["machines.csv"]

    sales = datasets["sales.csv"]
    production = datasets["production.csv"]
    maintenance = datasets["maintenance.csv"]
    financial = datasets["financial_transactions.csv"]
    budget = datasets["budget.csv"]
    energy = datasets["energy.csv"]
    emissions = datasets["emissions.csv"]
    waste = datasets["waste.csv"]
    inventory = datasets["inventory.csv"]

    relationships = [
        (
            sales,
            "account_id",
            accounts,
            "account_id",
            "Sales → Account",
        ),
        (
            sales,
            "customer_id",
            customers,
            "customer_id",
            "Sales → Customer",
        ),
        (
            sales,
            "product_id",
            products,
            "product_id",
            "Sales → Product",
        ),
        (
            sales,
            "location_id",
            locations,
            "location_id",
            "Sales → Location",
        ),
        (
            production,
            "product_id",
            products,
            "product_id",
            "Production → Product",
        ),
        (
            production,
            "location_id",
            locations,
            "location_id",
            "Production → Location",
        ),
        (
            production,
            "machine_id",
            machines,
            "machine_id",
            "Production → Machine",
        ),
        (
            production,
            "employee_id",
            employees,
            "employee_id",
            "Production → Employee",
        ),
        (
            maintenance,
            "location_id",
            locations,
            "location_id",
            "Maintenance → Location",
        ),
        (
            maintenance,
            "machine_id",
            machines,
            "machine_id",
            "Maintenance → Machine",
        ),
        (
            maintenance,
            "employee_id",
            employees,
            "employee_id",
            "Maintenance → Employee",
        ),
        (
            financial,
            "location_id",
            locations,
            "location_id",
            "Financial → Location",
        ),
        (
            budget,
            "location_id",
            locations,
            "location_id",
            "Budget → Location",
        ),
        (
            energy,
            "location_id",
            locations,
            "location_id",
            "Energy → Location",
        ),
        (
            emissions,
            "location_id",
            locations,
            "location_id",
            "Emissions → Location",
        ),
        (
            waste,
            "location_id",
            locations,
            "location_id",
            "Waste → Location",
        ),
        (
            inventory,
            "product_id",
            products,
            "product_id",
            "Inventory → Product",
        ),
        (
            inventory,
            "location_id",
            locations,
            "location_id",
            "Inventory → Location",
        ),
    ]

    for relationship in relationships:

        if not validate_id_relationship(*relationship):
            failures += 1

    # --------------------------------------------------------
    # Business consistency
    # --------------------------------------------------------

    print("\n7. Business consistency validation")

    customer_account = (
        customers[
            [
                "customer_id",
                "account_id",
            ]
        ]
        .drop_duplicates()
    )

    sales_customer_check = sales.merge(
        customer_account,
        on="customer_id",
        how="left",
        suffixes=(
            "_sales",
            "_customer",
        ),
    )

    account_mismatch = (
        sales_customer_check["account_id_sales"]
        != sales_customer_check["account_id_customer"]
    ).sum()

    if not check(
        account_mismatch == 0,
        "Sales account matches customer account",
        f"Sales contains {account_mismatch:,} "
        "customer/account mismatches",
    ):
        failures += 1

    # --------------------------------------------------------
    # Machine → Location
    # --------------------------------------------------------

    machine_location = (
        machines[
            [
                "machine_id",
                "location_id",
            ]
        ]
        .drop_duplicates()
    )

    production_machine_check = production.merge(
        machine_location,
        on="machine_id",
        how="left",
        suffixes=(
            "_production",
            "_machine",
        ),
    )

    production_location_mismatch = (
        production_machine_check["location_id_production"]
        != production_machine_check["location_id_machine"]
    ).sum()

    if not check(
        production_location_mismatch == 0,
        "Production machine location matches machine master",
        f"Production contains {production_location_mismatch:,} "
        "machine/location mismatches",
    ):
        failures += 1

    maintenance_machine_check = maintenance.merge(
        machine_location,
        on="machine_id",
        how="left",
        suffixes=(
            "_maintenance",
            "_machine",
        ),
    )

    maintenance_location_mismatch = (
        maintenance_machine_check["location_id_maintenance"]
        != maintenance_machine_check["location_id_machine"]
    ).sum()

    if not check(
        maintenance_location_mismatch == 0,
        "Maintenance machine location matches machine master",
        f"Maintenance contains {maintenance_location_mismatch:,} "
        "machine/location mismatches",
    ):
        failures += 1

    # --------------------------------------------------------
    # Employee → Location
    # --------------------------------------------------------

    employee_location = (
        employees[
            [
                "employee_id",
                "location_id",
            ]
        ]
        .drop_duplicates()
    )

    production_employee_check = production.merge(
        employee_location,
        on="employee_id",
        how="left",
        suffixes=(
            "_production",
            "_employee",
        ),
    )

    employee_location_mismatch = (
        production_employee_check["location_id_production"]
        != production_employee_check["location_id_employee"]
    ).sum()

    if not check(
        employee_location_mismatch == 0,
        "Production employee location matches employee master",
        f"Production contains {employee_location_mismatch:,} "
        "employee/location mismatches",
    ):
        failures += 1

    # --------------------------------------------------------
    # Numeric business rules
    # --------------------------------------------------------

    print("\n8. Numeric business-rule validation")

    sales_revenue = (
        sales["quantity"]
        * sales["unit_price"]
        - sales["discount_amount"]
    )

    revenue_difference = np.abs(
        sales_revenue
        - sales["revenue"]
    )

    revenue_mismatch = (
        revenue_difference > 0.01
    ).sum()

    if not check(
        revenue_mismatch == 0,
        "Sales revenue calculation is consistent",
        f"Sales contains {revenue_mismatch:,} "
        "revenue calculation mismatches",
    ):
        failures += 1

    if not check(
        (sales["quantity"] > 0).all(),
        "Sales quantities are positive",
        "Sales contains non-positive quantities",
    ):
        failures += 1

    if not check(
        (sales["unit_price"] > 0).all(),
        "Sales unit prices are positive",
        "Sales contains non-positive unit prices",
    ):
        failures += 1

    if not check(
        (production["planned_quantity"] >= 0).all(),
        "Production planned quantities are non-negative",
        "Production contains negative planned quantities",
    ):
        failures += 1

    if not check(
        (production["produced_quantity"] >= 0).all(),
        "Production quantities are non-negative",
        "Production contains negative produced quantities",
    ):
        failures += 1

    if not check(
        (
            production["defect_quantity"]
            <= production["produced_quantity"]
        ).all(),
        "Production defect quantity does not exceed production quantity",
        "Production contains invalid defect quantities",
    ):
        failures += 1

    if not check(
        (maintenance["maintenance_hours"] > 0).all(),
        "Maintenance hours are positive",
        "Maintenance contains non-positive maintenance hours",
    ):
        failures += 1

    if not check(
        (maintenance["downtime_hours"] >= 0).all(),
        "Maintenance downtime is non-negative",
        "Maintenance contains negative downtime",
    ):
        failures += 1

    # --------------------------------------------------------
    # Inventory grain
    # --------------------------------------------------------

    print("\n9. Inventory grain validation")

    inventory_duplicates = inventory.duplicated(
        subset=[
            "product_id",
            "location_id",
            "inventory_date",
        ]
    ).sum()

    if not check(
        inventory_duplicates == 0,
        "Inventory grain Date + Product + Location is unique",
        f"Inventory contains {inventory_duplicates:,} "
        "duplicate grain combinations",
    ):
        failures += 1

    inventory_calculated = (
        inventory["opening_quantity"]
        + inventory["received_quantity"]
        - inventory["issued_quantity"]
    )

    inventory_mismatch = (
        inventory_calculated
        != inventory["closing_quantity"]
    ).sum()

    if not check(
        inventory_mismatch == 0,
        "Inventory closing quantity reconciles",
        f"Inventory contains {inventory_mismatch:,} "
        "quantity reconciliation errors",
    ):
        failures += 1

    if not check(
        (inventory["closing_quantity"] >= 0).all(),
        "Inventory closing quantity is non-negative",
        "Inventory contains negative closing quantities",
    ):
        failures += 1

    # --------------------------------------------------------
    # Date validation
    # --------------------------------------------------------

    print("\n10. Date-range validation")

    date_columns = {
        "sales.csv": "transaction_date",
        "production.csv": "production_date",
        "maintenance.csv": "maintenance_date",
        "financial_transactions.csv": "transaction_date",
        "budget.csv": "budget_date",
        "energy.csv": "measurement_date",
        "emissions.csv": "emissions_date",
        "waste.csv": "waste_date",
        "inventory.csv": "inventory_date",
    }

    start_date = pd.Timestamp("2019-01-01")
    end_date = pd.Timestamp("2025-12-31")

    for filename, column in date_columns.items():

        dates = pd.to_datetime(
            datasets[filename][column]
        )

        invalid_dates = (
            (dates < start_date)
            | (dates > end_date)
        ).sum()

        if not check(
            invalid_dates == 0,
            f"{filename}: dates fall within approved range",
            f"{filename}: {invalid_dates:,} dates outside approved range",
        ):
            failures += 1

    # --------------------------------------------------------
    # Final result
    # --------------------------------------------------------

    print("\n" + "=" * 60)

    if failures == 0:

        print("BUSINESS DATA VALIDATION PASSED")
        print("The nine clean business datasets are ready.")
        print("=" * 60)

        return True

    print(
        f"BUSINESS DATA VALIDATION FAILED "
        f"WITH {failures} FAILURE(S)"
    )

    print("=" * 60)

    return False


# ============================================================
# Final Raw Data Validation
# ============================================================

def validate_final_data():

    print("=" * 60)
    print("Project Atlas — Final Raw Data Validation")
    print("Mode: QUALITY-ISSUE VALIDATION")
    print("=" * 60)

    print(
        "\nThe final raw layer is expected to contain "
        "controlled quality issues."
    )

    print(
        "This validation confirms the files exist, remain "
        "structurally usable, and contain the expected "
        "controlled defects."
    )

    datasets = {}

    for filename in EXPECTED_COUNTS:

        try:
            datasets[filename] = load_dataset(filename)

        except FileNotFoundError as error:
            print(f"FAIL  {error}")
            return False

    print("\n1. Record counts after quality injection")

    for filename, expected in EXPECTED_COUNTS.items():

        actual = len(datasets[filename])

        print(
            f"INFO  {filename}: "
            f"{actual:,} records"
        )

    print("\n2. Structural validation")

    failures = 0

    for filename, required in REQUIRED_COLUMNS.items():

        missing = (
            set(required)
            - set(datasets[filename].columns)
        )

        if not check(
            not missing,
            f"{filename}: required structure preserved",
            f"{filename}: missing columns {sorted(missing)}",
        ):
            failures += 1

    print("\n3. Expected quality issues")

    issue_summary = {}

    for filename, df in datasets.items():

        null_count = int(
            df.isna().sum().sum()
        )

        duplicate_rows = int(
            df.duplicated().sum()
        )

        issue_summary[filename] = {
            "null_cells": null_count,
            "duplicate_rows": duplicate_rows,
        }

        print(
            f"INFO  {filename}: "
            f"{null_count:,} null cells, "
            f"{duplicate_rows:,} duplicate rows"
        )

    total_nulls = sum(
        item["null_cells"]
        for item in issue_summary.values()
    )

    total_duplicates = sum(
        item["duplicate_rows"]
        for item in issue_summary.values()
    )

    if not check(
        total_nulls > 0,
        "Controlled missing values detected",
        "No missing values detected after quality injection",
    ):
        failures += 1

    if not check(
        total_duplicates > 0,
        "Controlled duplicate records detected",
        "No duplicate records detected after quality injection",
    ):
        failures += 1

    print("\n4. Final raw-data assessment")

    if failures == 0:

        print(
            "PASS  Final raw datasets contain the "
            "expected controlled quality issues."
        )

        print(
            "PASS  Final raw datasets remain structurally usable."
        )

        print("\n" + "=" * 60)
        print("FINAL RAW DATA VALIDATION PASSED")
        print("=" * 60)

        return True

    print("\n" + "=" * 60)
    print(
        f"FINAL RAW DATA VALIDATION FAILED "
        f"WITH {failures} FAILURE(S)"
    )
    print("=" * 60)

    return False


# ============================================================
# Main
# ============================================================

def main():

    final_mode = (
        len(sys.argv) > 1
        and sys.argv[1].lower() == "--final"
    )

    if final_mode:
        success = validate_final_data()
    else:
        success = validate_clean_data()

    sys.exit(0 if success else 1)


if __name__ == "__main__":
    main()
